const tokenIcons = {
  BLUR: "/tokens/BLUR.svg",
  bNEO: "/tokens/bNEO.svg",
  BUSD: "/tokens/BUSD.svg",
  USD: "/tokens/USD.svg",
  ETH: "/tokens/ETH.svg",
  GMX: "/tokens/GMX.svg",
  STEVMOS: "/tokens/stEVMOS.svg",
  LUNA: "/tokens/LUNA.svg",
  RATOM: "/tokens/rATOM.svg",
  STRD: "/tokens/STRD.svg",
  EVMOS: "/tokens/EVMOS.svg",
  IBCX: "/tokens/IBCX.svg",
  IRIS: "/tokens/IRIS.svg",
  ampLUNA: "/tokens/ampLUNA.svg",
  KUJI: "/tokens/KUJI.svg",
  STOSMO: "/tokens/stOSMO.svg",
  USDC: "/tokens/USDC.svg",
  axlUSDC: "/tokens/axlUSDC.svg",
  ATOM: "/tokens/ATOM.svg",
  STATOM: "/tokens/stATOM.svg",
  OSMO: "/tokens/OSMO.svg",
  rSWTH: "/tokens/rSWTH.svg",
  STLUNA: "/tokens/stLUNA.svg",
  LSI: "/tokens/LSI.svg",
  OKB: "/tokens/OKB.svg",
  OKT: "/tokens/OKT.svg",
  SWTH: "/tokens/SWTH.svg",
  USC: "/tokens/USC.svg",
  WBTC: "/tokens/WBTC.svg",
  wstETH: "/tokens/wstETH.svg",
  YieldUSD: "/tokens/YieldUSD.svg",
  ZIL: "/tokens/ZIL.svg",
};

export default tokenIcons;
